# Generated by Django 5.0.6 on 2024-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areax_ai_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicontentdb',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
