# Generated by Django 5.0.6 on 2024-06-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areax_ai_app', '0002_alter_aicontentdb_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aicontentdb',
            old_name='description',
            new_name='generated_contents',
        ),
    ]
