# Generated by Django 5.0.6 on 2024-07-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areax_ai_app', '0005_aicontentdb_email_usercredentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aicontentdb',
            old_name='generated_contents',
            new_name='caption',
        ),
    ]
