# Generated by Django 5.0.6 on 2024-08-22 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areax_ai_app', '0008_generatedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ai_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areax_ai_app.airesponse')),
            ],
        ),
    ]
