# Generated by Django 5.0.6 on 2024-08-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areax_ai_app', '0009_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenaAI_UsageDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('prompt_tokens', models.IntegerField()),
                ('completion_tokens', models.IntegerField()),
                ('total_tokens', models.IntegerField()),
                ('input_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('output_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
