# Generated by Django 5.0.6 on 2024-09-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areax_ai_app', '0010_openaai_usagedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponse',
            name='completion_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='input_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='output_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='total_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
