# Generated by Django 5.0.6 on 2025-04-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areax_ai_app', '0013_alter_chatsession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='user_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user_reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
