# Generated by Django 5.0.6 on 2025-04-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areax_ai_app', '0014_alter_chatsession_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartresponse',
            name='video_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartresponse',
            name='video_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
