# Generated by Django 5.0.6 on 2025-04-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areax_ai_app', '0015_smartresponse_video_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartresponse',
            name='audio_transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
