# Generated by Django 5.0.6 on 2025-05-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areax_ai_app', '0016_smartresponse_audio_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedSocialContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('original_caption', models.TextField(blank=True, null=True)),
                ('enhanced_caption', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('forwarded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
