# Generated by Django 5.0.6 on 2025-05-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areax_ai_app', '0017_enhancedsocialcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiImageEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('image_prompt', models.TextField()),
                ('original_image_name', models.CharField(max_length=255)),
                ('generated_image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
