# Generated by Django 5.0.6 on 2025-05-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areax_ai_app', '0018_geminiimageedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartresponse',
            name='user_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
